[project]
name = "nber-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "fake-useragent>=2.1.0",
    "lxml[html-clean]>=5.3.2",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
    "requests-html>=0.10.0",
    "selenium>=4.31.0",
    "webdriver-manager>=4.0.2",
]
